label stay_endings:
    n "You almost jump out of your skin when you feel something touch your arm."
    n "Aria hisses a whisper at you."
    a "SERENA!! Mom's gonna be really mad if she finds us down here!"
    n "Whatever game you were playing before, even Aria has dropped it in this place."
    a "I'm {i}suuuper{/i} not allowed in mom's workshop. I've never been down here before. She'll know we came in."
    n "Aria is preoccupied, glancing back at the stairs. Too worried about you and now her mom, she hasn't taken a good look around yet."
    s "Aria, this is very bad. Where is your mom?"
    s "Where is your mom right now?"
    a "She was already really, really, {i}really{/i} mad when I wasn't here. I didn't think she'd be leaving me alone again any time soon."
    a "But then she said something about /'pests in the forest/' and told me to stay here and wait until she came back."
    n "You know that your time is limited. This room, the stories you heard, the town's fears."
    n "You feel certain that if you're still here when Aria's mother returns, you will not survive."
    n "If the mob arrives instead, you're pretty sure the result will be the same."
    s "Aria, I don't want to scare you, and I don't say this as a game or to hurt you."
    s "Your mom made that damage in the forest. The one who's been taking people? It's her."
    n "You take a deep, shuddering breath. And then you drop the pit from your stomach into hers."
    s "And I'm pretty sure that if I'm still here when she gets back... she'll kill me."
    n "Aria stares at you and stammers weakly in protest."
    a "No- no, you've... You've been so nice to me, and you even said you'd stay! She wouldn't! She wouldn't..."
    s "Aria, do you remember the adventurers we met in the woods?"
    n "She nods. You direct her eyes up to the shelf in front of you."
    s "She... she's done something to them. Something very, very bad."
    s "I think I, this body, your... toy. I think I was someone else before. Someone who met the same fate as them and I don't know how many others."
    s "And when she comes back..."
    n "You swallow hard."
    s "That'll be me. Again."
    n "She stares at the doll-sized people for what feels like an eternity. Her own panicked tears begin to well in her green eyes."
    s "I know, I know it is a lot to process. But, Aria, I have to go-"
    n "She looks at you now. Her lip trembles."
    n "You take a deep breath, trying desperately to steady yourself."
    s "And I think you should come with me."
    n "You want to live, but you aren't prepared to sacrifice her to whatever life she might face here."
    n "This is also a lot of information all at once, most of it life-changing. You can see her mind spinning."
    n "You crouch down to her level, and you take her hands in yours."
    j "{i}You{/i} are my Weald Queen, Aria. And I, Jophiel, am your right hand."
    j "Enemies approach us now from several fronts. As your trusted guardian, your safety is paramount to me."
    j "But I am still new to this realm, and I require your might and cunning."
    s "Please, Aria.{p}I can't get us to safety alone."
    n "She considers you silently at first."
    n "The immediate dangers aside, the revelations you've brought seem to have shaken her, but not to her foundations."
    n "You suspect some part of her knew already. Her imagined worlds and daring escapades a welcome distraction from her harsh reality."
    a "We..."
    a "We probably can't just run away through the Weald."
    j "Right, you've got little legs."
    a "And Mom knows the forest reaaally well."
    n "Thinking about your options, she tugs on her hat nervously."
    n "But then she looks up, with a wide smile."
    a "Right! My hat! The buckle!"
    a "I'm not as skilled as Mom, but I could probably reverse the enchantment on it."
    j "What would that do?"
    a "Rather than bring me to her, it could send us away! Only..."
    j "Only?"
    a "I can't control where it goes. It might be really far from here."
    n "You're silent, thinking about her suggestion when you hear the door upstairs creak open."
    n "The way Aria freezes, you don't have to ask who it is."
    n "You take hold of her hands again."
    if bond1+bond2 == 2:
        j "It's okay, Aria. I'm here with you, and wherever we end up, I won't leave you alone."
        n "She nods and grips your hands tighter."
        n "She closes her eyes and pulls you close. Her buckle begins to glow with a deep purple hue."
        n "In an instant, the two of you are somewhere else. It isn't easy to start over when you don't know where you are or where you're going. But the two of you are together."
        n "Whether it be school, work, your relationships or your goals, you half-assed everything in your life before. But you throw yourself into this with determination you didn't know you had in you."
        n "You try to find opportunities to make Aria smile every day. It isn't easy taking care of someone else, but you can't imagine anything more worth doing."
        n "It's you and her in a new world. She summoned you because she needed you, and until she no longer needs you, you'll be by her side."
        return
    else:
        s "We need to go."
        n "Aria hesitates one last time."
        n "Then she throws her arms around you... and her hat on your head."
        a "Goodbye, Serena."
        n "In an instant, you are somewhere else."
        n "It isn't easy to start over when you don't know where you are, but you throw yourself into it. You have a destination, and you won't get there without all your effort."
        n "You know you came from the Kaistr Weald. There is a nearby capital city, Rimmond. You even remember the town's name, Woldthwaite."
        n "You ask a lot of questions, more than most people can even answer, but slowly you understand the basics of this foreign world."
        n "Once you have your bearings and save enough to buy a map, you return there. To the Weald. To Aria's cottage."
        n "The cottage is empty. The basement cleared out, and the attic, too. You don't know where Aria and her mother went, and the trail here goes cold."
        n "Without Aria, you are as unmoored in this world as you were in Cleveland. But you aren't stuck anymore, and you've proven resilient carving out a living here."
        n "You wanted to stay here as a second chance at living. You'll have to figure out what that means for yourself."
        return
