label go_home_endings:
    a "I'm fine. But we have to hurry, we're running out of time to send you back!"
    n "She's right. The sun is hastening it's descent. Darkness will be here soon."
    a "I have everything set up, already."
    n "She settles you down in the now-familiar circle. You take what will probably be your last look around this attic."
    n "You're oddly nostalgic for the space."
    a "Ahem."
    a "Are you ready to go?"
    q "fullBond"
    n "Some part of you wants to pepper Aria with questions, follow up on the concerns the mob from town raised on the way here."
    n "But you see how Aria is just barely holding together, resolved to honor her promise."
    n "You won't sully her effort, and you trust her. Whatever the truth may be."
    q "notFullBond"
    n "You think of the posse in the forest, the fears they shared, the trembling hands gripping their pitchforks."
    j "I didn't see your mom when I came in. Is she gone so soon after getting back?"
    a "No, she was... mad. I don't think she's gonna leave me alone again for a bit."
    n "You would expect her to be more excited about her mom being around more, but mostly Aria looks troubled."
    a "She only left just now to /'take care of some pests in the woods/.'"
    n "Your mind spins rational explanations. Perhaps she's already aware of it and going to go and aid the town with the Green-Eyed Demon." 
    n "Or... perhaps... There is a next question to ask, but you can't quite bring it to your lips before you notice the sky growing truly dark."
    n "You may not have every answer, in fact you're not sure you want them, but you do know for certain that you can't spend any more time searching."
    n "You need to go home."
    q "Resume"
    j "The sun is getting low, I'm as ready as I can be."
    n "You were asleep for this the first time, so you're not quite sure what to expect. You feel something like a static charge in your fur as the ritual begins."
    j "Thank you, Aria."
    j "Not just for sending me back, but for bringing me here, too. I'm glad it was me you summoned."
    n "Her facade finally cracks a little."
    a "I'll miss you."
    a "I'm grateful it was you, too."
    a "I hope things get better for you in Cleveland."
    j "Me too. I think they will.{p}I may not meet the requirements for your spell anymore, but you're welcome to peer in on me in your mirror anytime."
    j "And /'Jophiel/' will still be here for you when I'm gone."
    q "fullBond"
    a "I think I like Serena even better than Jophiel."
    n "You feel the magic swell beneath you. Your body grows light as your soul and conscious mind begin to separate."
    n "The last you see of this world is the tear stained smile of the young sorceress."
    n "When you woke up in your world again, it would have been easy enough to dismiss everything you experienced as nothing but a vivid dream."
    n "Even if you did lose far more time than usual \"sleeping.\" Even if your own body felt strangely foreign for a little while."
    n "Even if, around Halloween, the sight of a child in a witch hat made you choke up."
    n "You didn't dismiss it, though. It was real enough for you. And you were going to do what you told Aria you would: find ways to enjoy life again."
    n "After all, if she was going to look in on you from time to time, you wanted to make that an adventure."
    q "notFullBond"
    a "Yeah."
    n "You feel the magic swell beneath you. Your body grows light as your soul and conscious mind begin to separate."
    n "While you were focused on Aria, even your sensitive ears missed the footsteps on the stairs."
    n "The last you see of this world is the tear stained face of the young sorceress, gazing up, anxious, at her returned mother."
    n "You don't know what happened to her next."
    n "You returned to your world. If anyone noticed you were gone, they didn't show it."
    n "It would have been easy to dismiss everything that happened as a vivid dream. And you tried to. Even when you lost nearly a whole day \"sleeping.\" Even when your own body felt strangely foreign to you afterward."
    n "Even when, around Halloween, just the sight of a kid in a witch hat made your heart twist in your chest."
    n "You told yourself it was a dream. It had to be. Aria didn't exist except as some strange corner of your subconscious."
    n "One that was urging you to live life a little more like it matters, maybe."
    n "Or maybe just to call your mom."
    n "What was the other option, after all? If it was all real, if she did exist in some other world..."
    n "Then that hand on her shoulder was also real. And so was the look of dread in her eyes when she looked up."
    n "And also, just as real, was the fact that you left, and there's nothing you can do now."
    n "So you went back to your life. And you tried not to think about the strange dream, or the ways things might have changed if you had let them."

    return